### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by johnsaigle** [aces/DICAT#104]
Hey this should have a license! Maybe GPLv3 like LORIS?

**Comment by cmadjar** [comment]
Good point. Definitely like LORIS. Is there any paperwork involved in that or we should just write it out?

**Comment by johnsaigle** [comment]
@cmadjar I can make the PR if you want :) No paperwork afaik.

**Comment by johnsaigle** [comment]
#105

**Comment by cmadjar** [comment]
Merged! Thanks a lot. If you see anything else that might be missing, feel free to let me know and report an issue! :)
