### ISSUE TITLE
PatientName should not be empty, application will stall forever

### ISSUE THREAD

**Issue by gluneau** [aces/DICAT#76]
This error will occur if PatientName left blank and clicking De-identify

```
python DicAT_application.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1413, in __call__
    return self.func(*args)
  File "/home/gluneau/DICAT/dicat/dicom_anonymizer_frame.py", line 245, in collect_edited_data
    self.dirname, self.field_dict)
  File "/home/gluneau/DICAT/dicat/lib/dicom_anonymizer_methods.py", line 244, in dicom_zapping
    subdirs_list)
  File "/home/gluneau/DICAT/dicat/lib/dicom_anonymizer_methods.py", line 420, in create_directories
    os.mkdir(original_dir, 0755)
OSError: [Errno 17] File exists: '/home/gluneau/aaa/bbb/CCC6029_902717_V24_RES/'
```

See pull request #81

**Comment by cmadjar** [comment]
We should add a warning when the PatientName text field is empty and we click on Anonymize button to say that PatientName field is mandatory.

**Comment by driusan** [comment]
What if they want to anonymize for a reason other than putting it in LORIS, since it's a stand-alone program? Having an error message for a de-identification tool saying "Name is mandatory" seems counter-intuitive.

**Comment by gluneau** [comment]
The PatientName is being used as the new directory being created and the zip file names when it finishes.  

So we can either use another convention for these file names, or if not, we will have to make this field mandatory.

**Comment by cmadjar** [comment]
Yeah... I thought about that too but I remembered that it was specifically asked to add the PatientName to the file names so they can be directly uploaded into LORIS and people don't have to think about renaming the file to upload.

**Comment by cmadjar** [comment]
Maybe I could check if PatientName is set:
- if not, don't concatenate PatientName to original and anonymized.
- if set, concatenate PatientName to original and anonymized
